---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install xtra python stuff for python
  become: true
  package:
    name:
     - python3
     - python3-pip
     - python-pip
     - python3-setuptools
     - python-setuptools
     - xalan
    state: present

- name: install pip3 packages
  become: true
  pip:
    name:
     - setuptools
     - pytz
     - python-dateutil
    state: present
    executable: /usr/bin/pip3

- name: make shedule update
  become: true
  make:
    chdir: /home/info/content/
    target: all

- name: Create cronjob to get time data
  become: true
  cron:
    name: "update info-beamer shedule"
    minute: "*/15"
    job: "sleep 30; make -B -C /home/info/content/ all"
    user: root
    cron_file: '/etc/crontab'

- name: copy systemd file for info-beamer-timectrl
  become: true
  copy:
    src: info-beamer-timectrl.service
    dest: /etc/systemd/system/info-beamer-timectrl.service
    owner: root
    group: root
    mode: 0644

- name: restart info-beamer-timectrl.service
  become: true
  systemd: 
    state: restarted
    name: info-beamer-timectrl.service
    daemon_reload: yes
    enabled: yes
